import { Montserrat } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

const dayDream = localFont({ src: './font/daydream.woff2' })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montserrat.className}>{children}</body>
    </html>
  );
}
